### PR TITLE
@1aurabrown: update pricing label and add shipping info

### PR DESCRIPTION
**Pull request by xtina-starr**
This is the MG equivalent of https://github.com/artsy/force/pull/461 and updates the pricing label and adds shipping info https://github.com/artsy/collector-experience/issues/27

* this is to be merged after https://github.com/artsy/metaphysics/pull/488/commits/293b626c2db2b61ff1fd282969970b04bc00c284

screen shot 2016-12-06 at 7 35 31 pm

### CODE REVIEW

**Comment by xtina-starr** [comment]
In microgravity, prices already contain a label which doesn't affect works in an auction. We are going to keep this as is. Closing this PR as no change is needed.

screen shot 2016-12-08 at 1 22 05 pm

**Comment by alloy** [comment]
@xtina-starr Can you tell me why this was closed? I don’t see the pricing information in that screenshot, so I’m pretty sure this work still needs to be done.

**Comment by briansw** [comment]
@xtina-starr i think we just misunderstood each other here. We'd like to update the template as spec'd, but for works that are "Contact for price" it's fine to keep this existing template.

**Comment by xtina-starr** [comment]
@alloy I discussed with @briansw and I pointed out that this already contains a price label which inline with the price in the screen shot. The concern was that works in an auction shouldn't contain a price label and they don't because two different templates are used. From my understanding no work need to be done for this and it should remain as is.

**Comment by xtina-starr** [comment]
Ahh okay, @briansw.

**Comment by briansw** [comment]
Just following up to the last comment: we should not touch the template for any work in an auction whether upcoming, running, closed for both force and mg.

**Comment by xtina-starr** [comment]
@briansw I wanted to quickly revisit the discussion about the updates to the price label and addition of the shipping and tax copy. From my understanding, the addition of the shipping and tax copy is to help the user understand that additional fees could be associated with purchasing this work. If that's the case, I'm not sure that I understand why we are changing the styling and placement of the price label and price value in the case when there is a price.

**Comment by briansw** [comment]
@xtina-starr it's two things: 1) moving the templates to feel a little more ecommerce-y by drawing more attention to pricing information, and 2) to make note of additional fees the user may not be aware of.

**Comment by xtina-starr** [comment]
Closing this in favor of the new PR: https://github.com/artsy/microgravity/pull/73

**Pull request closed without merging**
