### PR TITLE
@sweir27: Update node + node modules

### PR DESCRIPTION
**Pull request by craigspaeth**
Our web apps are overdue for updated node + modules. Going to try and start with Microgravity. I'd also like to consider adding [Greenkeeper](https://greenkeeper.io/) to these projects.

### CODE REVIEW

**Comment by kanaabe** [comment]
For those mocha-related `Resolution method is overspecified` errors -- Mocha 3.x no longer wants a test return both a Promise and a callback. I've encountered these on Positron during the process of moving to Node 6 and was able to fix with: https://github.com/KyleAMathews/superagent-bluebird-promise/commit/ec2ac6b7f7c772c9e6a28cc8c1139ba9df601766

**Comment by craigspaeth** [comment]
😅  finally got a 💚  gonna poke around locally and merge if it looks good.

**Comment by kanaabe** [comment]
@craigspaeth Ah, deploy to staging _might_ fail -- I moved Semaphore back to NodeJS 5.11.1 for this morning's deploy. Sorry I forgot to change it back! I'll change it back to 6 once Joey's PR gets deployed to staging.

**Comment by craigspaeth** [comment]
@kanaabe no worries, I'll be babysitting MG/Force deploys/builds today regardless. Force & MG master are on Node 6 now so I'll just make sure the rest of our CI ducks are in a row.

**Pull request merged**
